export const MATCH_REQUEST = 'MATCH_REQUEST';
export const MATCH_RECEIVE_SUCCESS = 'MATCH_RECEIVE_SUCCESS';
export const MATCH_RECEIVE_FAIL = 'MATCH_RECEIVE_FAIL';
export const UI_SET_VIEWED_MATCH = 'UI_SET_VIEWED_MATCH';

export const PLAY_SUBMIT = 'PLAY_SUBMIT';
export const PLAY_SUBMIT_ROLLBACK = 'PLAY_SUBMIT_ROLLBACK';
export const PLAY_SUBMIT_COMMIT = 'PLAY_SUBMIT_COMMIT';
export const PLAY_ADD = 'PLAY_ADD';

export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS';
export const USER_AUTHENTICATE_FAIL = 'USER_AUTHENTICATE_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
