export const FIELD_GOAL_ATTEMPS = 'FIELD_GOAL_ATTEMPS';
export const FIELD_GOAL_MADE = 'FIELD_GOAL_MADE';
export const BLOCK_ATTEMPS = 'BLOCK_ATTEMPS';
export const BLOCK_MADE = 'BLOCK_MADE';
export const CATCH_SNITCH_ATTEMPS = 'CATCH_SNITCH_ATTEMPS';
export const CATCH_SNITCH_MADE = 'CATCH_SNITCH_MADE';
